linux 6.17.7 + shell fixes for linux/build.sh

diff --git a/linux/script/kernel_setup b/linux/script/kernel_setup
--- a/linux/script/kernel_setup
+++ b/linux/script/kernel_setup
@@ -5,27 +5,27 @@ kernel_extract_dir="linux/"
 download_artifacts_dir="artifacts/"
 keys_dir=$download_artifacts_dir"keys/"
 trusted_keys="torvalds@kernel.org gregkh@kernel.org"
-kernel_version="6.16.4"
-kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.16.4.tar.xz"
+kernel_version="6.17.7"
+kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.17.7.tar.xz"
 kernel_pgp="
 -----BEGIN PGP SIGNATURE-----
 Comment: This signature is for the .tar version of the archive
-Comment: git archive --format tar --prefix=linux-6.16.4/ v6.16.4
-Comment: git version 2.50.1
+Comment: git archive --format tar --prefix=linux-6.17.7/ v6.17.7
+Comment: git version 2.51.2
 
-iQIzBAABCgAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmiwaXoACgkQONu9yGCS
-aT7BChAAmu+gwtJvLxb67BjvCVAw/DwFstXZ3mq34Nbgu+ct+oPH6sUDBWnB80YS
-bK5M+B4eLA4qxRsq1FZxNo/tJpIA2qtW1NtVqStnlBeFG3i2IJJX2oZ392I5uFyF
-o2M6HudRjGsSviWNukbu0r/1EJV4AEEqauqu+4C7P8ZbknSJ6Gyjr/319wVDhHnT
-sdm8dCYg2Jpda/lAOiW6j42y+Jt9kEpy9ND2AwCTKDe8063Zbby6IMA9QGfYtO3f
-ZnovEgd8aa0Kvh6iXdrgSJfdddasF8c78bw+p8VEjw69U1L9l6dNXIi1aU1tP819
-Du63U9TjG7coShEpB91lfCDHdHDpkZSXCXlk/zRpb9y5TVcG42Bm3P3aC258dwSS
-L6NG6KBFu1ZtXy0X4xySWxJj1/MYJ5Vdm1SV4+WWZZ0QIo4Bdo4+UVFBl+wv9lPF
-lSBhdfgY3pO/E/TBwGGeAhVrqpIKEImpPWi4W5CKM2LcybCdJ41WCfO/aEBStL/p
-fEYsMyLMm/4q6U2ojPBDCvhJmCH/oCz2ndGVRencMYaCnX/9zb7rk7Z9zUeqWIpC
-Tphy0UOkYPLHc56ioeoSDKrkoMpwAIwLDBUwX9T65c3NmLmowfkZFAkEcYSwEpVA
-9z9iy6QgYTxlqpeE6AieMhr00NM8yUJmFDWVjvIxzQ7YGBGQDdM=
-=arwx
+iQIzBAABCgAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmkHWtoACgkQONu9yGCS
+aT4hNRAAhHPMrtyXJSfW+oOCz13qkN/EbT5dhsQ1h5GwCNBE5nlzAttRtkTFim9H
+MAZbw6+FdZ38GM5DKxme097elA0DjpOqYcDtjR4/yTHvhqOLsqCEhZF3QefHGs3Y
+b16hDB9gUOXwLvWQQM+r7KXiCgNwz0br7OaebS2ruASjbWJZ5whWQt6BlO20frmR
+721ChxtqSs8dubqbQubJuFie102KJ/HKg62iTNwLrVVv/XFgn/BUoBLiW8zf4NGR
+6mOXQfGuncN/wlWM+zxL0pktu9+Z2IocA+6IR2XEKBirj9hyXIZhMf4YJ+2ivA61
+akaJ2zZWroO2gmCXYaNBabwUbCbs0E80hP7SLnbmhfK8TE3XujUywUypF+FaMlWI
+iItfAHKXsuVhQZsiUrwrTC0RxBBIw+DVT9GRafywHyP38lJ2SJ/nbQunzn+AVok2
+9eYLeHfHNCpKLyU9uIYHGy46e9tKFTg9s7i5ygDJ3eNvSujgrXQdUcwAthnbEDRm
+18uub9yUxOUKyw8qK9L3y68BTVZ2BuWO6gMiq84OEssnafQNrlOVfAWRaX4qu5Vy
+JtKee+6I1guPBPGizE5uCvq6MCe+znFUU0oGUZukbKS1goXB6b3zFfybWY0Nu0jX
+tg/+PtNtk2amNK+sgH2m2dS+qcym8qQw84xXfu+sgk4Hn/idemU=
+=qGkc
 -----END PGP SIGNATURE-----
 "
 
@@ -61,3 +61,13 @@ mkdir -p $download_artifacts_dir
 mkdir -p $kernel_extract_dir
 
 extract_kernel
+
+# check for build dependencies
+build_required="bison flex bc gpg make gcc clang rustc"
+
+for pkg in $build_required; do
+    if ! command -v "$pkg" > /dev/null 2>&1; then
+        echo "$pkg is required to build the kernel. Please install it and try again."
+        exit 1
+    fi
+done
